### ISSUE TITLE
Pickle data truncated

### ISSUE THREAD

**Issue by mateusap1** [mateusap1/athena#1]
After mining a block for the third time, which took longer than the first one, the following error appeared when trying to send a request and the server stopped.
```
Traceback (most recent call last):
  File "src/Wallet.py", line 150, in <module>
    response = wallet.send_request("!get_chain", {})
  File "src/Wallet.py", line 79, in send_request
    response = pickle.loads(obj)
_pickle.UnpicklingError: pickle data was truncated
```

**Comment by mateusap1** [comment]
Actually, after analyzing it with more attention, the error happened when trying to display the chain and not when trying to send a request.

**Comment by mateusap1** [comment]
Is interesting that the block is taking a longer time to hash than the request even though the former has only four leading zeros and the latter has four.

**Comment by mateusap1** [comment]
Not using Pickle anymore
